/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.poo1;

import javax.swing.JOptionPane;

/**
 *
 * @author MarioSolis
 */
public class EstadisticaInterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form EstadisticaInterfazGrafica
     */
    public EstadisticaInterfazGrafica() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dialog_CSumatoria = new javax.swing.JDialog();
        Btn_calcularSumatoria = new javax.swing.JButton();
        Btn_volverCSumatoria = new javax.swing.JButton();
        Txt_valoresCSumatoria = new javax.swing.JTextField();
        Txt_resultCSumatoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dialog_CModa = new javax.swing.JDialog();
        Btn_calcularModa = new javax.swing.JButton();
        Btn_volverCModa = new javax.swing.JButton();
        Txt_valoresCModa = new javax.swing.JTextField();
        Txt_resultCModa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dialog_CPromedio = new javax.swing.JDialog();
        Btn_calcularPromedio = new javax.swing.JButton();
        Btn_volverCPromedio = new javax.swing.JButton();
        Txt_valoresCPromedio = new javax.swing.JTextField();
        Txt_resultCPromedio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dialog_CMediana = new javax.swing.JDialog();
        Btn_calcularMediana = new javax.swing.JButton();
        Btn_volverCMediana = new javax.swing.JButton();
        Txt_valoresCMediana = new javax.swing.JTextField();
        Txt_resultCMediana = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dialog_CVarianza = new javax.swing.JDialog();
        Btn_calcularVarianza = new javax.swing.JButton();
        Btn_volverCVarianza = new javax.swing.JButton();
        Txt_valoresCVarianza = new javax.swing.JTextField();
        Txt_resultCVarianza = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dialog_CDesviacionEstandar = new javax.swing.JDialog();
        Btn_calcularDesviacionEstandar = new javax.swing.JButton();
        Btn_volverCDesviacionEstandar = new javax.swing.JButton();
        Txt_valoresCDesviacionEstandar = new javax.swing.JTextField();
        Txt_resultCDesviacionEstandar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Lbl_menu = new javax.swing.JLabel();
        Rbtn_sumatoria = new javax.swing.JRadioButton();
        Rbtn_moda = new javax.swing.JRadioButton();
        Rbtn_promedio = new javax.swing.JRadioButton();
        Rbtn_mediana = new javax.swing.JRadioButton();
        Rbtn_varianza = new javax.swing.JRadioButton();
        Rbtn_desviacion = new javax.swing.JRadioButton();
        Btn_volver = new javax.swing.JButton();

        dialog_CSumatoria.setSize(new java.awt.Dimension(444, 299));

        Btn_calcularSumatoria.setText("Calcular");
        Btn_calcularSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_calcularSumatoriaActionPerformed(evt);
            }
        });

        Btn_volverCSumatoria.setText("Volver");
        Btn_volverCSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverCSumatoriaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Calcular Sumatoria");

        jLabel2.setText("Ingrese lista de valores númericos que desea incluir en el cálculo");

        jLabel3.setText("Resultado:");

        jLabel4.setText("divido por comas \",\":");

        javax.swing.GroupLayout dialog_CSumatoriaLayout = new javax.swing.GroupLayout(dialog_CSumatoria.getContentPane());
        dialog_CSumatoria.getContentPane().setLayout(dialog_CSumatoriaLayout);
        dialog_CSumatoriaLayout.setHorizontalGroup(
            dialog_CSumatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CSumatoriaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(dialog_CSumatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_CSumatoriaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(Txt_resultCSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(dialog_CSumatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dialog_CSumatoriaLayout.createSequentialGroup()
                            .addComponent(Txt_valoresCSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_calcularSumatoria))
                        .addGroup(dialog_CSumatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(dialog_CSumatoriaLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Btn_volverCSumatoria)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialog_CSumatoriaLayout.setVerticalGroup(
            dialog_CSumatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CSumatoriaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(dialog_CSumatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_valoresCSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_calcularSumatoria))
                .addGap(38, 38, 38)
                .addGroup(dialog_CSumatoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_resultCSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Btn_volverCSumatoria)
                .addGap(40, 40, 40))
        );

        dialog_CModa.setSize(new java.awt.Dimension(444, 299));

        Btn_calcularModa.setText("Calcular");
        Btn_calcularModa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_calcularModaActionPerformed(evt);
            }
        });

        Btn_volverCModa.setText("Volver");
        Btn_volverCModa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverCModaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Calcular Moda");

        jLabel6.setText("Ingrese lista de valores númericos que desea incluir en el cálculo");

        jLabel7.setText("Resultado:");

        jLabel8.setText("divido por comas \",\":");

        javax.swing.GroupLayout dialog_CModaLayout = new javax.swing.GroupLayout(dialog_CModa.getContentPane());
        dialog_CModa.getContentPane().setLayout(dialog_CModaLayout);
        dialog_CModaLayout.setHorizontalGroup(
            dialog_CModaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CModaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(dialog_CModaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_CModaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(Txt_resultCModa, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(dialog_CModaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dialog_CModaLayout.createSequentialGroup()
                            .addComponent(Txt_valoresCModa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_calcularModa))
                        .addGroup(dialog_CModaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)))
                    .addGroup(dialog_CModaLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Btn_volverCModa)
                        .addGap(127, 127, 127)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        dialog_CModaLayout.setVerticalGroup(
            dialog_CModaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CModaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(dialog_CModaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_valoresCModa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_calcularModa))
                .addGap(38, 38, 38)
                .addGroup(dialog_CModaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_resultCModa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Btn_volverCModa)
                .addGap(37, 37, 37))
        );

        dialog_CPromedio.setPreferredSize(new java.awt.Dimension(444, 299));
        dialog_CPromedio.setSize(new java.awt.Dimension(444, 299));

        Btn_calcularPromedio.setText("Calcular");
        Btn_calcularPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_calcularPromedioActionPerformed(evt);
            }
        });

        Btn_volverCPromedio.setText("Volver");
        Btn_volverCPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverCPromedioActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Calcular Promedio");

        jLabel10.setText("Ingrese lista de valores númericos que desea incluir en el cálculo");

        jLabel11.setText("Resultado:");

        jLabel12.setText("divido por comas \",\":");

        javax.swing.GroupLayout dialog_CPromedioLayout = new javax.swing.GroupLayout(dialog_CPromedio.getContentPane());
        dialog_CPromedio.getContentPane().setLayout(dialog_CPromedioLayout);
        dialog_CPromedioLayout.setHorizontalGroup(
            dialog_CPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CPromedioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(dialog_CPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_CPromedioLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(31, 31, 31)
                        .addComponent(Txt_resultCPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(dialog_CPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dialog_CPromedioLayout.createSequentialGroup()
                            .addComponent(Txt_valoresCPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_calcularPromedio))
                        .addGroup(dialog_CPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dialog_CPromedioLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Btn_volverCPromedio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialog_CPromedioLayout.setVerticalGroup(
            dialog_CPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CPromedioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(dialog_CPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_valoresCPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_calcularPromedio))
                .addGap(38, 38, 38)
                .addGroup(dialog_CPromedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_resultCPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Btn_volverCPromedio)
                .addGap(38, 38, 38))
        );

        dialog_CMediana.setPreferredSize(new java.awt.Dimension(444, 299));
        dialog_CMediana.setSize(new java.awt.Dimension(444, 299));

        Btn_calcularMediana.setText("Calcular");
        Btn_calcularMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_calcularMedianaActionPerformed(evt);
            }
        });

        Btn_volverCMediana.setText("Volver");
        Btn_volverCMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverCMedianaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Calcular Promedio");

        jLabel14.setText("Ingrese lista de valores númericos que desea incluir en el cálculo");

        jLabel15.setText("Resultado:");

        jLabel16.setText("divido por comas \",\":");

        javax.swing.GroupLayout dialog_CMedianaLayout = new javax.swing.GroupLayout(dialog_CMediana.getContentPane());
        dialog_CMediana.getContentPane().setLayout(dialog_CMedianaLayout);
        dialog_CMedianaLayout.setHorizontalGroup(
            dialog_CMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CMedianaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(dialog_CMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_CMedianaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(31, 31, 31)
                        .addComponent(Txt_resultCMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addGroup(dialog_CMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dialog_CMedianaLayout.createSequentialGroup()
                            .addComponent(Txt_valoresCMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_calcularMediana))
                        .addGroup(dialog_CMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)))
                    .addGroup(dialog_CMedianaLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Btn_volverCMediana)
                        .addGap(127, 127, 127)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        dialog_CMedianaLayout.setVerticalGroup(
            dialog_CMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CMedianaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(dialog_CMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_valoresCMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_calcularMediana))
                .addGap(38, 38, 38)
                .addGroup(dialog_CMedianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_resultCMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Btn_volverCMediana)
                .addGap(35, 35, 35))
        );

        dialog_CVarianza.setPreferredSize(new java.awt.Dimension(444, 299));
        dialog_CVarianza.setSize(new java.awt.Dimension(444, 299));

        Btn_calcularVarianza.setText("Calcular");
        Btn_calcularVarianza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_calcularVarianzaActionPerformed(evt);
            }
        });

        Btn_volverCVarianza.setText("Volver");
        Btn_volverCVarianza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverCVarianzaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Calcular Promedio");

        jLabel18.setText("Ingrese lista de valores númericos que desea incluir en el cálculo");

        jLabel19.setText("Resultado:");

        jLabel20.setText("divido por comas \",\":");

        javax.swing.GroupLayout dialog_CVarianzaLayout = new javax.swing.GroupLayout(dialog_CVarianza.getContentPane());
        dialog_CVarianza.getContentPane().setLayout(dialog_CVarianzaLayout);
        dialog_CVarianzaLayout.setHorizontalGroup(
            dialog_CVarianzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CVarianzaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(dialog_CVarianzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_CVarianzaLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(31, 31, 31)
                        .addComponent(Txt_resultCVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17)
                    .addGroup(dialog_CVarianzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dialog_CVarianzaLayout.createSequentialGroup()
                            .addComponent(Txt_valoresCVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_calcularVarianza))
                        .addGroup(dialog_CVarianzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18)))
                    .addGroup(dialog_CVarianzaLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Btn_volverCVarianza)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        dialog_CVarianzaLayout.setVerticalGroup(
            dialog_CVarianzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CVarianzaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(dialog_CVarianzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_valoresCVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_calcularVarianza))
                .addGap(38, 38, 38)
                .addGroup(dialog_CVarianzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_resultCVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Btn_volverCVarianza)
                .addGap(35, 35, 35))
        );

        dialog_CDesviacionEstandar.setPreferredSize(new java.awt.Dimension(444, 299));
        dialog_CDesviacionEstandar.setSize(new java.awt.Dimension(444, 299));

        Btn_calcularDesviacionEstandar.setText("Calcular");
        Btn_calcularDesviacionEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_calcularDesviacionEstandarActionPerformed(evt);
            }
        });

        Btn_volverCDesviacionEstandar.setText("Volver");
        Btn_volverCDesviacionEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverCDesviacionEstandarActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Calcular Desviación Estándar");

        jLabel22.setText("Ingrese lista de valores númericos que desea incluir en el cálculo");

        jLabel23.setText("Resultado:");

        jLabel24.setText("divido por comas \",\":");

        javax.swing.GroupLayout dialog_CDesviacionEstandarLayout = new javax.swing.GroupLayout(dialog_CDesviacionEstandar.getContentPane());
        dialog_CDesviacionEstandar.getContentPane().setLayout(dialog_CDesviacionEstandarLayout);
        dialog_CDesviacionEstandarLayout.setHorizontalGroup(
            dialog_CDesviacionEstandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CDesviacionEstandarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(dialog_CDesviacionEstandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_CDesviacionEstandarLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(31, 31, 31)
                        .addComponent(Txt_resultCDesviacionEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21)
                    .addGroup(dialog_CDesviacionEstandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dialog_CDesviacionEstandarLayout.createSequentialGroup()
                            .addComponent(Txt_valoresCDesviacionEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_calcularDesviacionEstandar))
                        .addGroup(dialog_CDesviacionEstandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22)))
                    .addGroup(dialog_CDesviacionEstandarLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Btn_volverCDesviacionEstandar)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        dialog_CDesviacionEstandarLayout.setVerticalGroup(
            dialog_CDesviacionEstandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_CDesviacionEstandarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(dialog_CDesviacionEstandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_valoresCDesviacionEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_calcularDesviacionEstandar))
                .addGap(38, 38, 38)
                .addGroup(dialog_CDesviacionEstandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_resultCDesviacionEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Btn_volverCDesviacionEstandar)
                .addGap(35, 35, 35))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_menu.setText("Menú Estadística");

        buttonGroup1.add(Rbtn_sumatoria);
        Rbtn_sumatoria.setText("Calcular Sumatoria");
        Rbtn_sumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_sumatoriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rbtn_moda);
        Rbtn_moda.setText("Calcular Moda");
        Rbtn_moda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_modaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rbtn_promedio);
        Rbtn_promedio.setText("Calcular Promedio");
        Rbtn_promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_promedioActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rbtn_mediana);
        Rbtn_mediana.setText("Calcular Mediana");
        Rbtn_mediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_medianaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rbtn_varianza);
        Rbtn_varianza.setText("Calcular Varianza");
        Rbtn_varianza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_varianzaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rbtn_desviacion);
        Rbtn_desviacion.setText("Calcular Desviación Estándar");
        Rbtn_desviacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_desviacionActionPerformed(evt);
            }
        });

        Btn_volver.setText("Volver");
        Btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(Lbl_menu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Btn_volver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rbtn_promedio)
                    .addComponent(Rbtn_moda)
                    .addComponent(Rbtn_sumatoria))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rbtn_desviacion)
                    .addComponent(Rbtn_varianza)
                    .addComponent(Rbtn_mediana))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Lbl_menu)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Rbtn_sumatoria)
                        .addGap(18, 18, 18)
                        .addComponent(Rbtn_moda)
                        .addGap(18, 18, 18)
                        .addComponent(Rbtn_promedio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Rbtn_mediana)
                        .addGap(18, 18, 18)
                        .addComponent(Rbtn_varianza)
                        .addGap(18, 18, 18)
                        .addComponent(Rbtn_desviacion)))
                .addGap(43, 43, 43)
                .addComponent(Btn_volver)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rbtn_sumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_sumatoriaActionPerformed
        this.setVisible(false);
        dialog_CSumatoria.setLocationRelativeTo(null);
        dialog_CSumatoria.setVisible(true);
    }//GEN-LAST:event_Rbtn_sumatoriaActionPerformed

    private void Rbtn_medianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_medianaActionPerformed
        this.setVisible(false);
        dialog_CMediana.setLocationRelativeTo(null);
        dialog_CMediana.setVisible(true);
    }//GEN-LAST:event_Rbtn_medianaActionPerformed

    private void Rbtn_desviacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_desviacionActionPerformed
        this.setVisible(false);
        dialog_CDesviacionEstandar.setLocationRelativeTo(null);
        dialog_CDesviacionEstandar.setVisible(true);
    }//GEN-LAST:event_Rbtn_desviacionActionPerformed

    private void Btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverActionPerformed
        this.setVisible(false);
        
        MenuInterfazGrafica volver = new MenuInterfazGrafica();
        volver.setVisible(true);
    }//GEN-LAST:event_Btn_volverActionPerformed

    private void Btn_calcularSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_calcularSumatoriaActionPerformed
        CalculadoraEstadistica calcular = new CalculadoraEstadistica();
        
        String valoresTexto = Txt_valoresCSumatoria.getText();
        
        if (valoresTexto.isEmpty() || valoresTexto.equals("0")){
            JOptionPane.showMessageDialog(null, "Debe ingresar al menos un valor y no puede ser nulo");
            
        } else {
            String[] partesTexto = valoresTexto.split(",");
            double[] valores = new double[partesTexto.length];
            for(int i =0; i < partesTexto.length; i ++){
                valores[i]=Double.parseDouble(partesTexto[i].trim());
            }
            Txt_resultCSumatoria.setText(String.valueOf(calcular.calcularSumatoria(valores)));
        }
        
        
    }//GEN-LAST:event_Btn_calcularSumatoriaActionPerformed

    private void Btn_volverCSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverCSumatoriaActionPerformed
        dialog_CSumatoria.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_Btn_volverCSumatoriaActionPerformed

    private void Btn_calcularModaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_calcularModaActionPerformed
        CalculadoraEstadistica calcular = new CalculadoraEstadistica();
        
        String valoresTexto = Txt_valoresCModa.getText();
        
        if (valoresTexto.isEmpty() || valoresTexto.equals("0")){
            JOptionPane.showMessageDialog(null, "Debe ingresar al menos un valor y no puede ser nulo");
            
        } else {
            String[] partesTexto = valoresTexto.split(",");
            double[] valores = new double[partesTexto.length];
            
            for(int i =0; i < partesTexto.length; i ++){
            valores[i]=Double.parseDouble(partesTexto[i].trim());
            
        }
        Txt_resultCModa.setText(String.valueOf(calcular.calcularModa(valores)));
        }
        
    }//GEN-LAST:event_Btn_calcularModaActionPerformed

    private void Btn_volverCModaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverCModaActionPerformed
        dialog_CModa.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_Btn_volverCModaActionPerformed

    private void Rbtn_modaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_modaActionPerformed
        this.setVisible(false);
        dialog_CModa.setLocationRelativeTo(null);
        dialog_CModa.setVisible(true);
    }//GEN-LAST:event_Rbtn_modaActionPerformed

    private void Btn_calcularPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_calcularPromedioActionPerformed
        CalculadoraEstadistica calcular = new CalculadoraEstadistica();
        
        String valoresTexto = Txt_valoresCPromedio.getText();
        
        if (valoresTexto.isEmpty() || valoresTexto.equals("0")){
            JOptionPane.showMessageDialog(null, "Debe ingresar al menos un valor y no puede ser nulo");
            
        } else {
            String[] partesTexto = valoresTexto.split(",");
            double[] valores = new double[partesTexto.length];
            
            for(int i =0; i < partesTexto.length; i ++){
            valores[i]=Double.parseDouble(partesTexto[i].trim());
            
        }
        Txt_resultCPromedio.setText(String.valueOf(calcular.calcularPromedio(valores)));
        }
    }//GEN-LAST:event_Btn_calcularPromedioActionPerformed

    private void Btn_volverCPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverCPromedioActionPerformed
        dialog_CPromedio.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_Btn_volverCPromedioActionPerformed

    private void Rbtn_promedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_promedioActionPerformed
        this.setVisible(false);
        dialog_CPromedio.setLocationRelativeTo(null);
        dialog_CPromedio.setVisible(true);
    }//GEN-LAST:event_Rbtn_promedioActionPerformed

    private void Btn_calcularMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_calcularMedianaActionPerformed
        CalculadoraEstadistica calcular = new CalculadoraEstadistica();
        
        String valoresTexto = Txt_valoresCMediana.getText();
        
        if (valoresTexto.isEmpty() || valoresTexto.equals("0")){
            JOptionPane.showMessageDialog(null, "Debe ingresar al menos un valor y no puede ser nulo");
            
        } else {
            String[] partesTexto = valoresTexto.split(",");
            double[] valores = new double[partesTexto.length];
            
            for(int i =0; i < partesTexto.length; i ++){
            valores[i]=Double.parseDouble(partesTexto[i].trim());
            
        }
        Txt_resultCMediana.setText(String.valueOf(calcular.calcularMediana(valores)));
        }
    }//GEN-LAST:event_Btn_calcularMedianaActionPerformed

    private void Btn_volverCMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverCMedianaActionPerformed
        dialog_CMediana.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_Btn_volverCMedianaActionPerformed

    private void Btn_calcularVarianzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_calcularVarianzaActionPerformed
        CalculadoraEstadistica calcular = new CalculadoraEstadistica();
        
        String valoresTexto = Txt_valoresCVarianza.getText();
        
        if (valoresTexto.isEmpty() || valoresTexto.equals("0")){
            JOptionPane.showMessageDialog(null, "Debe ingresar al menos un valor y no puede ser nulo");
            
        } else {
            String[] partesTexto = valoresTexto.split(",");
            double[] valores = new double[partesTexto.length];
            
            for(int i =0; i < partesTexto.length; i ++){
            valores[i]=Double.parseDouble(partesTexto[i].trim());
            
        }
        Txt_resultCVarianza.setText(String.valueOf(calcular.calcularVarianza(valores)));
        }
    }//GEN-LAST:event_Btn_calcularVarianzaActionPerformed

    private void Btn_volverCVarianzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverCVarianzaActionPerformed
        dialog_CVarianza.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_Btn_volverCVarianzaActionPerformed

    private void Rbtn_varianzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_varianzaActionPerformed
        this.setVisible(false);
        dialog_CVarianza.setLocationRelativeTo(null);
        dialog_CVarianza.setVisible(true);
    }//GEN-LAST:event_Rbtn_varianzaActionPerformed

    private void Btn_calcularDesviacionEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_calcularDesviacionEstandarActionPerformed
        CalculadoraEstadistica calcular = new CalculadoraEstadistica();
        
        String valoresTexto = Txt_valoresCDesviacionEstandar.getText();
        
        if (valoresTexto.isEmpty() || valoresTexto.equals("0")){
            JOptionPane.showMessageDialog(null, "Debe ingresar al menos un valor y no puede ser nulo");
            
        } else {
            String[] partesTexto = valoresTexto.split(",");
            double[] valores = new double[partesTexto.length];
            
            for(int i =0; i < partesTexto.length; i ++){
            valores[i]=Double.parseDouble(partesTexto[i].trim());
            
        }
        Txt_resultCDesviacionEstandar.setText(String.valueOf(calcular.calcularDesviacionEstandar(valores)));
        }
    }//GEN-LAST:event_Btn_calcularDesviacionEstandarActionPerformed

    private void Btn_volverCDesviacionEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverCDesviacionEstandarActionPerformed
        dialog_CDesviacionEstandar.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_Btn_volverCDesviacionEstandarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadisticaInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadisticaInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadisticaInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadisticaInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadisticaInterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_calcularDesviacionEstandar;
    private javax.swing.JButton Btn_calcularMediana;
    private javax.swing.JButton Btn_calcularModa;
    private javax.swing.JButton Btn_calcularPromedio;
    private javax.swing.JButton Btn_calcularSumatoria;
    private javax.swing.JButton Btn_calcularVarianza;
    private javax.swing.JButton Btn_volver;
    private javax.swing.JButton Btn_volverCDesviacionEstandar;
    private javax.swing.JButton Btn_volverCMediana;
    private javax.swing.JButton Btn_volverCModa;
    private javax.swing.JButton Btn_volverCPromedio;
    private javax.swing.JButton Btn_volverCSumatoria;
    private javax.swing.JButton Btn_volverCVarianza;
    private javax.swing.JLabel Lbl_menu;
    private javax.swing.JRadioButton Rbtn_desviacion;
    private javax.swing.JRadioButton Rbtn_mediana;
    private javax.swing.JRadioButton Rbtn_moda;
    private javax.swing.JRadioButton Rbtn_promedio;
    private javax.swing.JRadioButton Rbtn_sumatoria;
    private javax.swing.JRadioButton Rbtn_varianza;
    private javax.swing.JTextField Txt_resultCDesviacionEstandar;
    private javax.swing.JTextField Txt_resultCMediana;
    private javax.swing.JTextField Txt_resultCModa;
    private javax.swing.JTextField Txt_resultCPromedio;
    private javax.swing.JTextField Txt_resultCSumatoria;
    private javax.swing.JTextField Txt_resultCVarianza;
    private javax.swing.JTextField Txt_valoresCDesviacionEstandar;
    private javax.swing.JTextField Txt_valoresCMediana;
    private javax.swing.JTextField Txt_valoresCModa;
    private javax.swing.JTextField Txt_valoresCPromedio;
    private javax.swing.JTextField Txt_valoresCSumatoria;
    private javax.swing.JTextField Txt_valoresCVarianza;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog dialog_CDesviacionEstandar;
    private javax.swing.JDialog dialog_CMediana;
    private javax.swing.JDialog dialog_CModa;
    private javax.swing.JDialog dialog_CPromedio;
    private javax.swing.JDialog dialog_CSumatoria;
    private javax.swing.JDialog dialog_CVarianza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
