/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.poo1;

/**
 *
 * @author MarioSolis
 */
public class MenuInterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuInterfazGrafica() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_menu = new javax.swing.JLabel();
        Rbtn_areas = new javax.swing.JRadioButton();
        Rbtn_perimetros = new javax.swing.JRadioButton();
        Rbtn_estadisticas = new javax.swing.JRadioButton();
        Rbtn_conjeturas = new javax.swing.JRadioButton();
        Btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_menu.setText("Menú");

        Rbtn_areas.setText("Áreas de figuras planas (2D)");
        Rbtn_areas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_areasActionPerformed(evt);
            }
        });

        Rbtn_perimetros.setText("Perímetros de figuras planas (2D)");
        Rbtn_perimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_perimetrosActionPerformed(evt);
            }
        });

        Rbtn_estadisticas.setText("Estadísticas");
        Rbtn_estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_estadisticasActionPerformed(evt);
            }
        });

        Rbtn_conjeturas.setText("Conjeturas");
        Rbtn_conjeturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_conjeturasActionPerformed(evt);
            }
        });

        Btn_salir.setText("Salir");
        Btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(Lbl_menu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rbtn_perimetros)
                            .addComponent(Rbtn_areas)
                            .addComponent(Rbtn_estadisticas)
                            .addComponent(Rbtn_conjeturas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(Btn_salir)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Lbl_menu)
                .addGap(18, 18, 18)
                .addComponent(Rbtn_areas)
                .addGap(18, 18, 18)
                .addComponent(Rbtn_perimetros)
                .addGap(18, 18, 18)
                .addComponent(Rbtn_estadisticas)
                .addGap(18, 18, 18)
                .addComponent(Rbtn_conjeturas)
                .addGap(30, 30, 30)
                .addComponent(Btn_salir)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rbtn_areasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_areasActionPerformed
        AreasInterfazGrafica siguiente = new AreasInterfazGrafica();
        
        this.setVisible(false);
        siguiente.setVisible(true);
    }//GEN-LAST:event_Rbtn_areasActionPerformed

    private void Rbtn_perimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_perimetrosActionPerformed
        PerimetrosInterfazGrafica siguiente = new PerimetrosInterfazGrafica();
        
        this.setVisible(false);
        siguiente.setVisible(true);
    }//GEN-LAST:event_Rbtn_perimetrosActionPerformed

    private void Rbtn_estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_estadisticasActionPerformed
        EstadisticaInterfazGrafica siguiente = new EstadisticaInterfazGrafica();
        
        this.setVisible(false);
        siguiente.setVisible(true);
    }//GEN-LAST:event_Rbtn_estadisticasActionPerformed

    private void Rbtn_conjeturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_conjeturasActionPerformed
        MenuConjInterGraf siguiente = new MenuConjInterGraf();
        
        this.setVisible(false);
        siguiente.setVisible(true);
    }//GEN-LAST:event_Rbtn_conjeturasActionPerformed

    private void Btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_salir;
    private javax.swing.JLabel Lbl_menu;
    private javax.swing.JRadioButton Rbtn_areas;
    private javax.swing.JRadioButton Rbtn_conjeturas;
    private javax.swing.JRadioButton Rbtn_estadisticas;
    private javax.swing.JRadioButton Rbtn_perimetros;
    // End of variables declaration//GEN-END:variables
}
