/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.poo1;

/**
 *
 * @author MarioSolis
 */
public class MenuConjInterGraf extends javax.swing.JFrame {

    /**
     * Creates new form MenuConjInterGraf
     */
    public MenuConjInterGraf() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_menuconj = new javax.swing.JLabel();
        Btn_volver = new javax.swing.JButton();
        Rbtn_Ulmann = new javax.swing.JRadioButton();
        Rbtn_Gilbreath = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_menuconj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_menuconj.setText("Menu Conjeturas");

        Btn_volver.setText("Volver");
        Btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverActionPerformed(evt);
            }
        });

        Rbtn_Ulmann.setText("Conjetura de Ulmann");
        Rbtn_Ulmann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_UlmannActionPerformed(evt);
            }
        });

        Rbtn_Gilbreath.setText("Conjetura Gilbreath");
        Rbtn_Gilbreath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_GilbreathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(Btn_volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rbtn_Gilbreath)
                            .addComponent(Rbtn_Ulmann)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Lbl_menuconj)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Lbl_menuconj)
                .addGap(45, 45, 45)
                .addComponent(Rbtn_Ulmann)
                .addGap(34, 34, 34)
                .addComponent(Rbtn_Gilbreath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(Btn_volver)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverActionPerformed
        MenuInterfazGrafica volver = new MenuInterfazGrafica();

        this.setVisible(false);
        volver.setVisible(true);
    }//GEN-LAST:event_Btn_volverActionPerformed

    private void Rbtn_UlmannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_UlmannActionPerformed
        UlmannInterfazGrafica volver = new UlmannInterfazGrafica();

        this.setVisible(false);
        volver.setVisible(true);
    }//GEN-LAST:event_Rbtn_UlmannActionPerformed

    private void Rbtn_GilbreathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_GilbreathActionPerformed
        GilbreathInterfazGrafica volver = new GilbreathInterfazGrafica();

        this.setVisible(false);
        volver.setVisible(true);
    }//GEN-LAST:event_Rbtn_GilbreathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConjInterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConjInterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConjInterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConjInterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConjInterGraf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_volver;
    private javax.swing.JLabel Lbl_menuconj;
    private javax.swing.JRadioButton Rbtn_Gilbreath;
    private javax.swing.JRadioButton Rbtn_Ulmann;
    // End of variables declaration//GEN-END:variables
}
