/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.poo1;

/**
 *
 * @author MarioSolis
 */
public class UlmannInterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form UlmannInterfazGrafica
     */
    public UlmannInterfazGrafica() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_ulmann = new javax.swing.JLabel();
        Lbl_num = new javax.swing.JLabel();
        Txt_num = new javax.swing.JTextField();
        Btn_calcular = new javax.swing.JButton();
        Lbl_resultado = new javax.swing.JLabel();
        Btn_volver = new javax.swing.JButton();
        Lbl_resul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_ulmann.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_ulmann.setText("Conjetura Ulmann");

        Lbl_num.setText("Ingrese un número");

        Txt_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_numActionPerformed(evt);
            }
        });

        Btn_calcular.setText("Calcular");
        Btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_calcularActionPerformed(evt);
            }
        });

        Lbl_resultado.setText("Resultado:");

        Btn_volver.setText("Volver");
        Btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_volverActionPerformed(evt);
            }
        });

        Lbl_resul.setEnabled(false);
        Lbl_resul.setMaximumSize(new java.awt.Dimension(20, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(Lbl_ulmann, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_num)
                        .addGap(38, 38, 38)
                        .addComponent(Txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Btn_calcular))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_resultado)
                        .addGap(46, 46, 46)
                        .addComponent(Lbl_resul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_volver)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Lbl_ulmann)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_num)
                    .addComponent(Txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_calcular))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_resultado)
                    .addComponent(Lbl_resul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(Btn_volver)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_calcularActionPerformed
        ConjeturaUlmann ulmann =new ConjeturaUlmann();
        ulmann.setNum(Double.parseDouble(Txt_num.getText()));
        ulmann.calcular();
        
        Lbl_resul.setEnabled(true);
        Lbl_resul.setText(String.valueOf(ulmann.resultado));
    }//GEN-LAST:event_Btn_calcularActionPerformed

    private void Txt_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_numActionPerformed

    private void Btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_volverActionPerformed
        MenuConjInterGraf volver = new MenuConjInterGraf();
        
        this.setVisible(false);
        volver.setVisible(true);
    }//GEN-LAST:event_Btn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UlmannInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UlmannInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UlmannInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UlmannInterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UlmannInterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_calcular;
    private javax.swing.JButton Btn_volver;
    private javax.swing.JLabel Lbl_num;
    private javax.swing.JLabel Lbl_resul;
    private javax.swing.JLabel Lbl_resultado;
    private javax.swing.JLabel Lbl_ulmann;
    private javax.swing.JTextField Txt_num;
    // End of variables declaration//GEN-END:variables
}
