/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.oo;

import javax.swing.JOptionPane;

public class PerimetrosInterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form PerimetrosInterfazGrafica
     */
    public PerimetrosInterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogCirculo = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        inputCirculo = new javax.swing.JTextField();
        calcularCirculoButton = new javax.swing.JButton();
        atrasCirculo = new javax.swing.JButton();
        resultadoCirculo = new javax.swing.JLabel();
        dialogTriangulo = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        inputTriangulo1 = new javax.swing.JTextField();
        calcularTriaungulo = new javax.swing.JButton();
        atrasTriangulo = new javax.swing.JButton();
        resultadoTriangulo = new javax.swing.JLabel();
        inputTriangulo2 = new javax.swing.JTextField();
        inputTriangulo3 = new javax.swing.JTextField();
        dialogCuadrado = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        inputCuadrado = new javax.swing.JTextField();
        calcularCuadradoButton1 = new javax.swing.JButton();
        atrasCuadrado = new javax.swing.JButton();
        resultadoCuadrado = new javax.swing.JLabel();
        dialogRectangulo = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        inputRectangulo1 = new javax.swing.JTextField();
        inputRectangulo2 = new javax.swing.JTextField();
        calcularRectanguloButton2 = new javax.swing.JButton();
        atrasRectangulo = new javax.swing.JButton();
        resultadoRectangulo = new javax.swing.JLabel();
        dialogRombo = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        inputRombo = new javax.swing.JTextField();
        calcularRomboButton = new javax.swing.JButton();
        atrasRombo = new javax.swing.JButton();
        resultadoRombo = new javax.swing.JLabel();
        dialogRomboide = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        inputRomboide1 = new javax.swing.JTextField();
        inputRomboide2 = new javax.swing.JTextField();
        calcularRomboideButton = new javax.swing.JButton();
        atrasRomboide = new javax.swing.JButton();
        resultadoRomboide = new javax.swing.JLabel();
        dialogTrapecio = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        inputTrapecio1 = new javax.swing.JTextField();
        inputTrapecio2 = new javax.swing.JTextField();
        inputTrapecio3 = new javax.swing.JTextField();
        inputTrapecio4 = new javax.swing.JTextField();
        calcularTrapecioButton = new javax.swing.JButton();
        atrasTrapecio = new javax.swing.JButton();
        resultadoTrapecio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dialogPoligonoRegular = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        inputPoligono1 = new javax.swing.JTextField();
        inputPoligono2 = new javax.swing.JTextField();
        inputPoligono3 = new javax.swing.JTextField();
        calcularPoligono = new javax.swing.JButton();
        atrasPoligono = new javax.swing.JButton();
        resultadoPoligono = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dialogAtras = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        siguiente = new javax.swing.JButton();
        circuloButton1 = new javax.swing.JRadioButton();
        trianguloButton2 = new javax.swing.JRadioButton();
        cuadradoButton3 = new javax.swing.JRadioButton();
        rectanguloButton4 = new javax.swing.JRadioButton();
        romboButton5 = new javax.swing.JRadioButton();
        romboideButton6 = new javax.swing.JRadioButton();
        trapecioButton7 = new javax.swing.JRadioButton();
        poligonoRegularButton8 = new javax.swing.JRadioButton();
        atras = new javax.swing.JButton();

        dialogCirculo.setSize(new java.awt.Dimension(800, 500));

        jLabel2.setText("Ingrese el radio del círculo:");

        inputCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCirculoActionPerformed(evt);
            }
        });

        calcularCirculoButton.setText("Calcular");
        calcularCirculoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularCirculoButtonActionPerformed(evt);
            }
        });

        atrasCirculo.setText("Atrás");
        atrasCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasCirculoActionPerformed(evt);
            }
        });

        resultadoCirculo.setText("Resultado");

        javax.swing.GroupLayout dialogCirculoLayout = new javax.swing.GroupLayout(dialogCirculo.getContentPane());
        dialogCirculo.getContentPane().setLayout(dialogCirculoLayout);
        dialogCirculoLayout.setHorizontalGroup(
            dialogCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCirculoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dialogCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCirculoLayout.createSequentialGroup()
                        .addComponent(atrasCirculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcularCirculoButton))
                    .addComponent(jLabel2)
                    .addComponent(inputCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        dialogCirculoLayout.setVerticalGroup(
            dialogCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCirculoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(inputCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(dialogCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularCirculoButton)
                    .addComponent(atrasCirculo))
                .addGap(50, 50, 50)
                .addComponent(resultadoCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        dialogTriangulo.setSize(new java.awt.Dimension(800, 500));

        jLabel3.setText("Ingrese los lados del triángulo:");

        inputTriangulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTriangulo1ActionPerformed(evt);
            }
        });

        calcularTriaungulo.setText("Calcular");
        calcularTriaungulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularTriaunguloActionPerformed(evt);
            }
        });

        atrasTriangulo.setText("Atrás");
        atrasTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasTrianguloActionPerformed(evt);
            }
        });

        resultadoTriangulo.setText("Resultado");

        inputTriangulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTriangulo2ActionPerformed(evt);
            }
        });

        inputTriangulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTriangulo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogTrianguloLayout = new javax.swing.GroupLayout(dialogTriangulo.getContentPane());
        dialogTriangulo.getContentPane().setLayout(dialogTrianguloLayout);
        dialogTrianguloLayout.setHorizontalGroup(
            dialogTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTrianguloLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dialogTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTriangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTriangulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(inputTriangulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogTrianguloLayout.createSequentialGroup()
                        .addComponent(atrasTriangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcularTriaungulo)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        dialogTrianguloLayout.setVerticalGroup(
            dialogTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTrianguloLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(inputTriangulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputTriangulo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputTriangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(dialogTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atrasTriangulo)
                    .addComponent(calcularTriaungulo))
                .addGap(18, 18, 18)
                .addComponent(resultadoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        dialogCuadrado.setSize(new java.awt.Dimension(800, 500));

        jLabel4.setText("Ingrese un lado del cuadrado:");

        inputCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCuadradoActionPerformed(evt);
            }
        });

        calcularCuadradoButton1.setText("Calcular");
        calcularCuadradoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularCuadradoButton1ActionPerformed(evt);
            }
        });

        atrasCuadrado.setText("Atrás");
        atrasCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasCuadradoActionPerformed(evt);
            }
        });

        resultadoCuadrado.setText("Resultado");

        javax.swing.GroupLayout dialogCuadradoLayout = new javax.swing.GroupLayout(dialogCuadrado.getContentPane());
        dialogCuadrado.getContentPane().setLayout(dialogCuadradoLayout);
        dialogCuadradoLayout.setHorizontalGroup(
            dialogCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCuadradoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dialogCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogCuadradoLayout.createSequentialGroup()
                        .addComponent(atrasCuadrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcularCuadradoButton1))
                    .addComponent(jLabel4)
                    .addComponent(inputCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogCuadradoLayout.setVerticalGroup(
            dialogCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCuadradoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(inputCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(dialogCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularCuadradoButton1)
                    .addComponent(atrasCuadrado))
                .addGap(50, 50, 50)
                .addComponent(resultadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogRectangulo.setSize(new java.awt.Dimension(800, 500));

        jLabel5.setText("Ingrese el largo y ancho del rectángulo:");

        inputRectangulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRectangulo1ActionPerformed(evt);
            }
        });

        inputRectangulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRectangulo2ActionPerformed(evt);
            }
        });

        calcularRectanguloButton2.setText("Calcular");
        calcularRectanguloButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRectanguloButton2ActionPerformed(evt);
            }
        });

        atrasRectangulo.setText("Atrás");
        atrasRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasRectanguloActionPerformed(evt);
            }
        });

        resultadoRectangulo.setText("Resultado");

        javax.swing.GroupLayout dialogRectanguloLayout = new javax.swing.GroupLayout(dialogRectangulo.getContentPane());
        dialogRectangulo.getContentPane().setLayout(dialogRectanguloLayout);
        dialogRectanguloLayout.setHorizontalGroup(
            dialogRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRectanguloLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dialogRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputRectangulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogRectanguloLayout.createSequentialGroup()
                        .addComponent(atrasRectangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcularRectanguloButton2))
                    .addComponent(jLabel5)
                    .addComponent(inputRectangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogRectanguloLayout.setVerticalGroup(
            dialogRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRectanguloLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(inputRectangulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputRectangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atrasRectangulo)
                    .addComponent(calcularRectanguloButton2))
                .addGap(18, 18, 18)
                .addComponent(resultadoRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogRombo.setSize(new java.awt.Dimension(800, 500));

        jLabel6.setText("Ingrese un lado del rombo:");

        inputRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRomboActionPerformed(evt);
            }
        });

        calcularRomboButton.setText("Calcular");
        calcularRomboButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRomboButtonActionPerformed(evt);
            }
        });

        atrasRombo.setText("Atrás");
        atrasRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasRomboActionPerformed(evt);
            }
        });

        resultadoRombo.setText("Resultado");

        javax.swing.GroupLayout dialogRomboLayout = new javax.swing.GroupLayout(dialogRombo.getContentPane());
        dialogRombo.getContentPane().setLayout(dialogRomboLayout);
        dialogRomboLayout.setHorizontalGroup(
            dialogRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRomboLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dialogRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogRomboLayout.createSequentialGroup()
                        .addComponent(atrasRombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcularRomboButton))
                    .addComponent(jLabel6)
                    .addComponent(inputRombo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoRombo, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogRomboLayout.setVerticalGroup(
            dialogRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRomboLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(inputRombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(dialogRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularRomboButton)
                    .addComponent(atrasRombo))
                .addGap(50, 50, 50)
                .addComponent(resultadoRombo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogRomboide.setSize(new java.awt.Dimension(800, 500));

        jLabel7.setText("Ingrese la base y la altura del Romboide:");

        inputRomboide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRomboide1ActionPerformed(evt);
            }
        });

        inputRomboide2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRomboide2ActionPerformed(evt);
            }
        });

        calcularRomboideButton.setText("Calcular");
        calcularRomboideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRomboideButtonActionPerformed(evt);
            }
        });

        atrasRomboide.setText("Atrás");
        atrasRomboide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasRomboideActionPerformed(evt);
            }
        });

        resultadoRomboide.setText("Resultado");

        javax.swing.GroupLayout dialogRomboideLayout = new javax.swing.GroupLayout(dialogRomboide.getContentPane());
        dialogRomboide.getContentPane().setLayout(dialogRomboideLayout);
        dialogRomboideLayout.setHorizontalGroup(
            dialogRomboideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRomboideLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dialogRomboideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputRomboide1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogRomboideLayout.createSequentialGroup()
                        .addComponent(atrasRomboide)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calcularRomboideButton))
                    .addComponent(jLabel7)
                    .addComponent(inputRomboide2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoRomboide, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogRomboideLayout.setVerticalGroup(
            dialogRomboideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRomboideLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(inputRomboide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputRomboide2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogRomboideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atrasRomboide)
                    .addComponent(calcularRomboideButton))
                .addGap(18, 18, 18)
                .addComponent(resultadoRomboide, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogTrapecio.setSize(new java.awt.Dimension(800, 500));

        jLabel8.setText("Ingrese la base mayor y la base menor del Trapecio:");

        inputTrapecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTrapecio1ActionPerformed(evt);
            }
        });

        inputTrapecio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTrapecio2ActionPerformed(evt);
            }
        });

        inputTrapecio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTrapecio3ActionPerformed(evt);
            }
        });

        inputTrapecio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTrapecio4ActionPerformed(evt);
            }
        });

        calcularTrapecioButton.setText("Calcular");
        calcularTrapecioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularTrapecioButtonActionPerformed(evt);
            }
        });

        atrasTrapecio.setText("Atrás");
        atrasTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasTrapecioActionPerformed(evt);
            }
        });

        resultadoTrapecio.setText("Resultado");

        jLabel9.setText("Ingrese la longitud del lado 1 y el lado 2 del Trapecio:");

        javax.swing.GroupLayout dialogTrapecioLayout = new javax.swing.GroupLayout(dialogTrapecio.getContentPane());
        dialogTrapecio.getContentPane().setLayout(dialogTrapecioLayout);
        dialogTrapecioLayout.setHorizontalGroup(
            dialogTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTrapecioLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dialogTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTrapecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTrapecio4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(inputTrapecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(inputTrapecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogTrapecioLayout.createSequentialGroup()
                        .addComponent(atrasTrapecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcularTrapecioButton)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        dialogTrapecioLayout.setVerticalGroup(
            dialogTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTrapecioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTrapecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTrapecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTrapecio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTrapecio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(dialogTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calcularTrapecioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atrasTrapecio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadoTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        dialogPoligonoRegular.setSize(new java.awt.Dimension(800, 500));

        jLabel11.setText("Ingrese el número de lados del polígono:");

        inputPoligono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPoligono1ActionPerformed(evt);
            }
        });

        inputPoligono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPoligono2ActionPerformed(evt);
            }
        });

        inputPoligono3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPoligono3ActionPerformed(evt);
            }
        });

        calcularPoligono.setText("Calcular");
        calcularPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularPoligonoActionPerformed(evt);
            }
        });

        atrasPoligono.setText("Atrás");
        atrasPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasPoligonoActionPerformed(evt);
            }
        });

        resultadoPoligono.setText("Resultado");

        jLabel12.setText("Ingrese el nombre del polígono:");

        jLabel13.setText("Ingrese la longitud de uno de los lados:");

        javax.swing.GroupLayout dialogPoligonoRegularLayout = new javax.swing.GroupLayout(dialogPoligonoRegular.getContentPane());
        dialogPoligonoRegular.getContentPane().setLayout(dialogPoligonoRegularLayout);
        dialogPoligonoRegularLayout.setHorizontalGroup(
            dialogPoligonoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPoligonoRegularLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(dialogPoligonoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(inputPoligono3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(inputPoligono1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(inputPoligono2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogPoligonoRegularLayout.createSequentialGroup()
                        .addComponent(atrasPoligono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcularPoligono)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        dialogPoligonoRegularLayout.setVerticalGroup(
            dialogPoligonoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPoligonoRegularLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPoligono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPoligono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPoligono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(dialogPoligonoRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularPoligono)
                    .addComponent(atrasPoligono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadoPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        dialogAtras.setSize(new java.awt.Dimension(400, 400));

        jLabel10.setText("Volviendo al menu principal...");

        javax.swing.GroupLayout dialogAtrasLayout = new javax.swing.GroupLayout(dialogAtras.getContentPane());
        dialogAtras.getContentPane().setLayout(dialogAtrasLayout);
        dialogAtrasLayout.setHorizontalGroup(
            dialogAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAtrasLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel10)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        dialogAtrasLayout.setVerticalGroup(
            dialogAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAtrasLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel10)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcular Perimetro");

        jLabel1.setText("Seleccione la figura para calcular el perímetro:");

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        circuloButton1.setText("1. Círculo");
        circuloButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuloButton1ActionPerformed(evt);
            }
        });

        trianguloButton2.setText("2. Triángulo");
        trianguloButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trianguloButton2ActionPerformed(evt);
            }
        });

        cuadradoButton3.setText("3. Cuadrado");
        cuadradoButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadradoButton3ActionPerformed(evt);
            }
        });

        rectanguloButton4.setText("4. Rectángulo");

        romboButton5.setText("5. Rombo");

        romboideButton6.setText("6. Romboide");

        trapecioButton7.setText("7. Trapecio");

        poligonoRegularButton8.setText("8. Otro polígono regular");
        poligonoRegularButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poligonoRegularButton8ActionPerformed(evt);
            }
        });

        atras.setText("Atrás");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(circuloButton1)
                    .addComponent(jLabel1)
                    .addComponent(trianguloButton2)
                    .addComponent(cuadradoButton3)
                    .addComponent(rectanguloButton4)
                    .addComponent(romboButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(romboideButton6)
                    .addComponent(trapecioButton7)
                    .addComponent(poligonoRegularButton8))
                .addGap(389, 389, 389))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(siguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circuloButton1)
                    .addComponent(romboideButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trianguloButton2)
                    .addComponent(trapecioButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadradoButton3)
                    .addComponent(poligonoRegularButton8))
                .addGap(18, 18, 18)
                .addComponent(rectanguloButton4)
                .addGap(18, 18, 18)
                .addComponent(romboButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente)
                    .addComponent(atras))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuadradoButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadradoButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadradoButton3ActionPerformed

    private void poligonoRegularButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poligonoRegularButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poligonoRegularButton8ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        dialogAtras.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void trianguloButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trianguloButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trianguloButton2ActionPerformed

    private void inputCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCirculoActionPerformed

    private void calcularCirculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularCirculoButtonActionPerformed

        String inputText = inputCirculo.getText().trim(); // Trim to remove leading/trailing spaces
        if (inputText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un número para el radio del círculo.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double radio = Double.parseDouble(inputText);

            if (radio <= 0) {
                JOptionPane.showMessageDialog(this, "El radio del círculo debe ser mayor que cero.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Circulo circulo = new Circulo(radio, "Círculo");

            String resultado = Imprimir.imprimirPerimetro(circulo);

            resultadoCirculo.setText(resultado);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para el radio del círculo.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_calcularCirculoButtonActionPerformed

    private void inputTriangulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTriangulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTriangulo1ActionPerformed

    private void calcularTriaunguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularTriaunguloActionPerformed
        // Validate and parse input
        String inputText1 = inputTriangulo1.getText().trim();
        String inputText2 = inputTriangulo2.getText().trim();
        String inputText3 = inputTriangulo3.getText().trim();

        if (inputText1.isEmpty() || inputText2.isEmpty() || inputText3.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los tres lados del triángulo.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double lado1 = Double.parseDouble(inputText1);
            double lado2 = Double.parseDouble(inputText2);
            double lado3 = Double.parseDouble(inputText3);

            if (lado1 <= 0 || lado2 <= 0 || lado3 <= 0) {
                JOptionPane.showMessageDialog(this, "Los lados del triángulo deben ser mayores que cero.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validar que es un triangulo: la suma de dos lados es mayor que la del tercer lado
            if (lado1 + lado2 <= lado3 || lado1 + lado3 <= lado2 || lado2 + lado3 <= lado1) {
                JOptionPane.showMessageDialog(this, "Ups! No se trata de un triángulo. Los lados no cumplen con la desigualdad del triángulo.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Triangulo triangulo = new Triangulo(lado1, lado2, lado3, "Triángulo");

            String resultado = Imprimir.imprimirPerimetro(triangulo);

            resultadoTriangulo.setText(resultado);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese números válidos para los lados del triángulo.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_calcularTriaunguloActionPerformed

    private void inputTriangulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTriangulo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTriangulo2ActionPerformed

    private void inputTriangulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTriangulo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTriangulo3ActionPerformed

    private void inputCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCuadradoActionPerformed

    private void calcularCuadradoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularCuadradoButton1ActionPerformed
        String inputText = inputCuadrado.getText().trim();

        if (inputText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo Vacío! Ingrese el lado del cuadrado.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double lado = Double.parseDouble(inputText);

            if (lado <= 0) {
                JOptionPane.showMessageDialog(this, "El lado del cuadrado debe ser mayor que cero.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Cuadrado cuadrado = new Cuadrado(lado, "Cuadrado");

            String resultado = Imprimir.imprimirPerimetro(cuadrado);

            resultadoCuadrado.setText(resultado);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido para el lado del cuadrado.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_calcularCuadradoButton1ActionPerformed

    private void inputRectangulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRectangulo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRectangulo2ActionPerformed

    private void calcularRectanguloButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRectanguloButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularRectanguloButton2ActionPerformed

    private void inputRectangulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRectangulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRectangulo1ActionPerformed

    private void inputRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRomboActionPerformed

    private void calcularRomboButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRomboButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularRomboButtonActionPerformed

    private void inputRomboide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRomboide1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRomboide1ActionPerformed

    private void inputRomboide2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRomboide2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRomboide2ActionPerformed

    private void calcularRomboideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRomboideButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularRomboideButtonActionPerformed

    private void inputTrapecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTrapecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTrapecio1ActionPerformed

    private void inputTrapecio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTrapecio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTrapecio2ActionPerformed

    private void calcularTrapecioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularTrapecioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularTrapecioButtonActionPerformed

    private void inputTrapecio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTrapecio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTrapecio3ActionPerformed

    private void inputTrapecio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTrapecio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTrapecio4ActionPerformed

    private void inputPoligono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPoligono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPoligono1ActionPerformed

    private void inputPoligono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPoligono2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPoligono2ActionPerformed

    private void inputPoligono3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPoligono3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPoligono3ActionPerformed

    private void calcularPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularPoligonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularPoligonoActionPerformed


    private void circuloButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuloButton1ActionPerformed

    }//GEN-LAST:event_circuloButton1ActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        int selectedCount = 0;
        if (circuloButton1.isSelected()) {
            selectedCount++;
        }
        if (trianguloButton2.isSelected()) {
            selectedCount++;
        }
        if (cuadradoButton3.isSelected()) {
            selectedCount++;
        }
        if (rectanguloButton4.isSelected()) {
            selectedCount++;
        }
        if (romboButton5.isSelected()) {
            selectedCount++;
        }
        if (romboideButton6.isSelected()) {
            selectedCount++;
        }
        if (trapecioButton7.isSelected()) {
            selectedCount++;
        }
        if (poligonoRegularButton8.isSelected()) {
            selectedCount++;
        }

        if (selectedCount != 1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una figura para calcular el perímetro.", "Error de selección", JOptionPane.ERROR_MESSAGE);
        } else {
            if (circuloButton1.isSelected()) {
                dialogCirculo.setVisible(true);
            } else if (trianguloButton2.isSelected()) {
                dialogTriangulo.setVisible(true);
            } else if (cuadradoButton3.isSelected()) {
                dialogCuadrado.setVisible(true);
            } else if (rectanguloButton4.isSelected()) {
                dialogRectangulo.setVisible(true);
            } else if (romboButton5.isSelected()) {
                dialogRombo.setVisible(true);
            } else if (romboideButton6.isSelected()) {
                dialogRomboide.setVisible(true);
            } else if (trapecioButton7.isSelected()) {
                dialogTrapecio.setVisible(true);
            } else if (poligonoRegularButton8.isSelected()) {
                dialogPoligonoRegular.setVisible(true);
            }
        }

    }//GEN-LAST:event_siguienteActionPerformed

    private void atrasCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasCirculoActionPerformed
        dialogCirculo.setVisible(false);
    }//GEN-LAST:event_atrasCirculoActionPerformed

    private void atrasTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasTrianguloActionPerformed
        dialogTriangulo.setVisible(false);
    }//GEN-LAST:event_atrasTrianguloActionPerformed

    private void atrasCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasCuadradoActionPerformed
        dialogCuadrado.setVisible(false);
    }//GEN-LAST:event_atrasCuadradoActionPerformed

    private void atrasRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasRectanguloActionPerformed
        dialogRectangulo.setVisible(false);
    }//GEN-LAST:event_atrasRectanguloActionPerformed

    private void atrasRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasRomboActionPerformed
        dialogRombo.setVisible(false);
    }//GEN-LAST:event_atrasRomboActionPerformed

    private void atrasRomboideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasRomboideActionPerformed
        dialogRomboide.setVisible(false);
    }//GEN-LAST:event_atrasRomboideActionPerformed

    private void atrasTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasTrapecioActionPerformed
        dialogTrapecio.setVisible(false);
    }//GEN-LAST:event_atrasTrapecioActionPerformed

    private void atrasPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasPoligonoActionPerformed
        dialogPoligonoRegular.setVisible(false);
    }//GEN-LAST:event_atrasPoligonoActionPerformed

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerimetrosInterfazGrafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerimetrosInterfazGrafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerimetrosInterfazGrafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerimetrosInterfazGrafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PerimetrosInterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton atrasCirculo;
    private javax.swing.JButton atrasCuadrado;
    private javax.swing.JButton atrasPoligono;
    private javax.swing.JButton atrasRectangulo;
    private javax.swing.JButton atrasRombo;
    private javax.swing.JButton atrasRomboide;
    private javax.swing.JButton atrasTrapecio;
    private javax.swing.JButton atrasTriangulo;
    private javax.swing.JButton calcularCirculoButton;
    private javax.swing.JButton calcularCuadradoButton1;
    private javax.swing.JButton calcularPoligono;
    private javax.swing.JButton calcularRectanguloButton2;
    private javax.swing.JButton calcularRomboButton;
    private javax.swing.JButton calcularRomboideButton;
    private javax.swing.JButton calcularTrapecioButton;
    private javax.swing.JButton calcularTriaungulo;
    private javax.swing.JRadioButton circuloButton1;
    private javax.swing.JRadioButton cuadradoButton3;
    private javax.swing.JDialog dialogAtras;
    private javax.swing.JDialog dialogCirculo;
    private javax.swing.JDialog dialogCuadrado;
    private javax.swing.JDialog dialogPoligonoRegular;
    private javax.swing.JDialog dialogRectangulo;
    private javax.swing.JDialog dialogRombo;
    private javax.swing.JDialog dialogRomboide;
    private javax.swing.JDialog dialogTrapecio;
    private javax.swing.JDialog dialogTriangulo;
    private javax.swing.JTextField inputCirculo;
    private javax.swing.JTextField inputCuadrado;
    private javax.swing.JTextField inputPoligono1;
    private javax.swing.JTextField inputPoligono2;
    private javax.swing.JTextField inputPoligono3;
    private javax.swing.JTextField inputRectangulo1;
    private javax.swing.JTextField inputRectangulo2;
    private javax.swing.JTextField inputRombo;
    private javax.swing.JTextField inputRomboide1;
    private javax.swing.JTextField inputRomboide2;
    private javax.swing.JTextField inputTrapecio1;
    private javax.swing.JTextField inputTrapecio2;
    private javax.swing.JTextField inputTrapecio3;
    private javax.swing.JTextField inputTrapecio4;
    private javax.swing.JTextField inputTriangulo1;
    private javax.swing.JTextField inputTriangulo2;
    private javax.swing.JTextField inputTriangulo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton poligonoRegularButton8;
    private javax.swing.JRadioButton rectanguloButton4;
    private javax.swing.JLabel resultadoCirculo;
    private javax.swing.JLabel resultadoCuadrado;
    private javax.swing.JLabel resultadoPoligono;
    private javax.swing.JLabel resultadoRectangulo;
    private javax.swing.JLabel resultadoRombo;
    private javax.swing.JLabel resultadoRomboide;
    private javax.swing.JLabel resultadoTrapecio;
    private javax.swing.JLabel resultadoTriangulo;
    private javax.swing.JRadioButton romboButton5;
    private javax.swing.JRadioButton romboideButton6;
    private javax.swing.JButton siguiente;
    private javax.swing.JRadioButton trapecioButton7;
    private javax.swing.JRadioButton trianguloButton2;
    // End of variables declaration//GEN-END:variables
}
